server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: signin
          uri: http://localhost:8081
          predicates:
            - Path=/v1/signin
        - id: products
          uri: http://localhost:8082
          predicates:
            - Path=/v1/products
