# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Run tests of sign in service
      working-directory: ./signin
      run: mvn test
#    - name: Run tests of list products service
#      working-directory: ./listpoducts
#      run: mvn test
#    - name: Run tests of api gateway
#      working-directory: ./apigateway
#      run: mvn test